### PR TITLE
Quick Start guide update

### PR DESCRIPTION
**Pull request by BlizzyFox**
I updated the images and instructions in the quick start guide to match the current appearance and usage of Kanna Protecc. The instructions are edited for clarity and brevity for beginner friendliness. On my fork there is also a wiki that includes more information, advanced usages and FAQs. https://github.com/BlizzyFox/AntiRip/wiki I cannot include the wiki in the pull request but I'd like to submit it for review to be added to the main repo.

### CODE REVIEW

**Comment by MistressPlague** [comment]
Some minor misspellings, no issue; but saying using creator companion will cause people to think that is the only supported SDK type, it'd be worth changing it to say VRCSDK vaguely, linking to the vrchat site

**Comment by MistressPlague** [comment]
Overall, awesome work

**Comment by MistressPlague** [comment]
As for the wiki, having the advanced usage above the quick start may be confusing, as people tend to go top-down

**Comment by MistressPlague** [comment]
Overall, a wiki page may not be ideal, but using a readme with other .md files for other pages, like advanced usage; as wiki is separate to the main .md file(s), maintaining it is not trivial.

**Comment by MistressPlague** [comment]
I will do these fixes. Thanks for contributing <3

**Comment by BlizzyFox** [comment]
I thought VRChat deprecated all other SDKs and now only distribute SDKs through the Creator companion. Though that's a minor detail. and changing the link to that would be a non-issue. 

I'm not sure if there is a way to change the github wiki order I can look into it. 

I do still think having the wiki available as a place to find extra information is a good thing. I'd like to help maintain the wiki.

**Comment by MistressPlague** [comment]
They still offer non VCC VRCSDK for older avatars that depend on it.

I think the "wiki" should be done in .md files form, not with github's wiki system, as it just introduces more work without much reward.

**Pull request merged**
